# Generated by Django 2.1 on 2019-04-07 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='interface_user',
        ),
    ]
